export const ErrorCode = {
  INVALID_DATA: 'INVALID_DATA',
  DOUBLE_REPORT: 'DOUBLE_REPORT',
  GEMINI_ERROR: 'GEMINI_ERROR',
  UPLOAD_IMAGE_ERROR: 'UPLOAD_IMAGE_ERROR',
  MEASURE_NOT_FOUND: 'MEASURE_NOT_FOUND',
  CONFIRMATION_DUPLICATE: 'CONFIRMATION_DUPLICATE',
  INVALID_TYPE: 'INVALID_TYPE',
} as const;
